# Generated by Django 5.0.6 on 2024-06-12 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='name',
            field=models.CharField(default='*', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=10),
        ),
    ]
